# Site settings
name: Walker Code Ranger

title: "Walker Code Ranger Blog"
url: "https://WalkerCodeRanger.com"
encoding: UTF-8
permalink: /blog/:year/:month/:title/
paginate: 5
paginate_path: "/blog/page:num"
repository: WalkerCodeRanger/WalkerCodeRanger.github.io
author:
  name: Jeff Walker Code Ranger
  email: Jeff@WalkerCodeRanger.com

# Build settings
markdown: kramdown
incremental: false # still experimental and seems to be causing problems
strict_front_matter: true

plugins:
  - jekyll-redirect-from
#  - jekyll-feed

# Exclude from processing.
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
