name: Walker Code Ranger
markdown: redcarpet
pygments: true
encoding: UTF-8
permalink: /blog/:year/:month/:title
paginate: 5
paginate_path: "/blog/page:num"
url: "http://WalkerCodeRanger.com"
title: "Walker Code Ranger Blog"
author:
  name: Jeff Walker Code Ranger
  email: Jeff@WalkerCodeRanger.com